--- Initial values from mailing list 14 Apr 2013

insert into Member (id, name, email) values (1,'a.tapio.vaananen@gmail.com','Antti Väänänen')
insert into Member (id, name, email) values (2,'aahlback@cc.hut.fi','Andreas Ahlbäck')
insert into Member (id, name, email) values (3,'alitovaara@gmail.com','Aku')
insert into Member (id, name, email) values (4,'andreasahlback10@gmail.com','Andreas Ahlbäck')
insert into Member (id, name, email) values (5,'anna.hakonen@helsinki.fi','Anna Hakonen')
insert into Member (id, name, email) values (6,'anna.palojarvi@iki.fi','Anna Palojärvi')
insert into Member (id, name, email) values (7,'annaleena.ikkala@gmail.com','annaleena.ikkala@gmail.com')
insert into Member (id, name, email) values (8,'anne.j.dahlgren@gmail.com','Anne')
insert into Member (id, name, email) values (9,'antony@cyberiantiger.org','CyberTiger')
insert into Member (id, name, email) values (10,'antti.kansala@gmail.com','Antti Känsälä')
insert into Member (id, name, email) values (11,'antti.vaananen@espoo.opit.fi','puttonen')
insert into Member (id, name, email) values (12,'antti@innamaa.com','antti')
insert into Member (id, name, email) values (13,'apa@surf.fi','Antti Niemi')
insert into Member (id, name, email) values (14,'arvi.timgren@helsinki.fi','Carl-Johan Timgren')
insert into Member (id, name, email) values (15,'beatawillman@gmail.com','Beata Willman')
insert into Member (id, name, email) values (16,'belina.bjork@gmail.com','Belina Björk')
insert into Member (id, name, email) values (17,'bijoux33@hotmail.com','Biju Surf')
insert into Member (id, name, email) values (18,'cathrineelisehenriksson@gmail.com','Cathrine Henriksson')
insert into Member (id, name, email) values (19,'chrisseb@gmail.com','Christian')
insert into Member (id, name, email) values (20,'danielblinnikka@gmail.com','Daniel Blinnikka')
insert into Member (id, name, email) values (21,'eeva.ylismaa@finnair.com','Ylismaa Eeva')
insert into Member (id, name, email) values (22,'ekku.rytkon@gmail.com','Ekku')
insert into Member (id, name, email) values (23,'esa.overmark@gmail.com','Esa Övermark')
insert into Member (id, name, email) values (24,'ewokmausoleum@gmail.com','Marius Marcellus')
insert into Member (id, name, email) values (25,'fabian.bjork@aller.fi','Fabian Björk')
insert into Member (id, name, email) values (26,'fin312@gmail.com','Anders Smeds')
insert into Member (id, name, email) values (27,'hagman.niina@gmail.com','Ninsku')
insert into Member (id, name, email) values (28,'Hanna.Issakainen@parexel.com','Issakainen Hanna')
insert into Member (id, name, email) values (29,'hanna.tukiainen@gmail.com','Hanna Tukiainen')
insert into Member (id, name, email) values (30,'heidiharju1@gmail.com','Heidi Harju')
insert into Member (id, name, email) values (31,'heidiharju@welho.com','Heidi Harju')
insert into Member (id, name, email) values (32,'heikki.winberg@iki.fi','Heikki Winberg')
insert into Member (id, name, email) values (33,'heikkiilvessalo@gmail.com','heikki.ilvessalo@castren.fi')
insert into Member (id, name, email) values (34,'henkka.nyman@gmail.com','henkka.nyman@gmail.com')
insert into Member (id, name, email) values (35,'henri.kronlund@gmail.com','Henri Kronlund')
insert into Member (id, name, email) values (36,'hjunnila@cc.hut.fi','hjunnila@cc.hut.fi')
insert into Member (id, name, email) values (37,'hlitovaara@gmail.com','Hanna Litovaara')
insert into Member (id, name, email) values (38,'hlmika.stenman@gmail.com','Mika Stenman')
insert into Member (id, name, email) values (39,'holopainen.miia@gmail.com','Miia Holopainen')
insert into Member (id, name, email) values (40,'ida.hakola@gmail.com','Ida Hakola')
insert into Member (id, name, email) values (41,'immo.heino@vtt.fi','Heino Immo')
insert into Member (id, name, email) values (42,'immoheino@gmail.com','Immo')
insert into Member (id, name, email) values (43,'jaan.praks@tkk.fi','Jaan Praks')
insert into Member (id, name, email) values (44,'jaana.mellanen@luukku.com','jaana.mellanen@luukku.com')
insert into Member (id, name, email) values (45,'jacob.segercrantz@gmail.com','Jacke')
insert into Member (id, name, email) values (46,'jani.hienonen@gmail.com','Jani')
insert into Member (id, name, email) values (47,'jani.paavolainen@welho.com','Jani Paavolainen')
insert into Member (id, name, email) values (48,'janipaavolainen@gmail.com','surfing ry')
insert into Member (id, name, email) values (49,'janne.junttila@luukku.com','Janne J')
insert into Member (id, name, email) values (50,'jari.hamalainen@nice.fi','Jari')
insert into Member (id, name, email) values (51,'jarno@ddb.fi','Jarno Lindblom')
insert into Member (id, name, email) values (52,'jennihovinen@gmail.com','Jenni Hovinen')
insert into Member (id, name, email) values (53,'jesper.broo@processvision.fi','Broo Jesper')
insert into Member (id, name, email) values (54,'jhaavanlammi@gmail.com','Johannes Haavanlammi')
insert into Member (id, name, email) values (55,'jisihvon@cc.hut.fi','Jarkko Sihvonen')
insert into Member (id, name, email) values (56,'jkleinon@gmail.com','Jani')
insert into Member (id, name, email) values (57,'jmunkki@gmail.com','Juri Munkki')
insert into Member (id, name, email) values (58,'joahtola@gmail.com','Johanna Ahtola')
insert into Member (id, name, email) values (59,'joge80@yahoo.com','JoGe')
insert into Member (id, name, email) values (60,'joge@surf.fi','joge@surf.fi')
insert into Member (id, name, email) values (61,'johanna.eve@netti.fi','Johanna Hinkkanen')
insert into Member (id, name, email) values (62,'johannes.haavanlammi@outotec.com','johannes.haavanlammi')
insert into Member (id, name, email) values (63,'johannes.kokkila@gmail.com','Jossu')
insert into Member (id, name, email) values (64,'joonas_tuhkuri@hotmail.com','joonas_tuhkuri@hotmail.com')
insert into Member (id, name, email) values (65,'josefine.hackman@gmail.com','Josefine Hackman')
insert into Member (id, name, email) values (66,'josetez@wippies.fi','josetez@wippies.fi')
insert into Member (id, name, email) values (67,'juha.blinnikka@elisanet.fi','juha.blinnikka@elisanet.fi')
insert into Member (id, name, email) values (68,'juhahaanpera@gmail.com','Juha Haanperä')
insert into Member (id, name, email) values (69,'juhahaanpera@hotmail.com','juhahaanpera@hotmail.com')
insert into Member (id, name, email) values (70,'juhahaanperasurfing@gmail.com','Juha Haanperä')
insert into Member (id, name, email) values (71,'juho.mikkonen@kopparberg.fi','juho.mikkonen@kopparberg.fi')
insert into Member (id, name, email) values (72,'juhoikkala@gmail.com','juhoik')
insert into Member (id, name, email) values (73,'jun.kojima@vtt.fi','Jun Kojima')
insert into Member (id, name, email) values (74,'jussi.harju@steinmann.fi','Jussi Harju')
insert into Member (id, name, email) values (75,'jussi.kallasvuo@gmail.com','Jussi')
insert into Member (id, name, email) values (76,'jusu1@kolumbus.fi','Jusu')
insert into Member (id, name, email) values (77,'kaarle.makinen@gmail.com','Kaarle Mäkinen')
insert into Member (id, name, email) values (78,'kaisaryynanen@gmail.com','Kaisa')
insert into Member (id, name, email) values (79,'kalle_holle@hotmail.com','surffari')
insert into Member (id, name, email) values (80,'kati.hannukainen@gmail.com','Kati')
insert into Member (id, name, email) values (81,'kim.hagman@gmail.com','Kim Hagman')
insert into Member (id, name, email) values (82,'kirill.tarassov@gmail.com','KirKir')
insert into Member (id, name, email) values (83,'kolari.kari@gmail.com','Kolari.Kari')
insert into Member (id, name, email) values (84,'kristian.englund@gmail.com','Kristian Englund')
insert into Member (id, name, email) values (85,'laura.puustinen@fimnet.fi','Laura Puustinen')
insert into Member (id, name, email) values (86,'lauri.kajosaari@helsinki.fi','lauri')
insert into Member (id, name, email) values (87,'maija.salmela@tse.fi','Maija')
insert into Member (id, name, email) values (88,'mail.moonfruit@gmail.com','Sanna')
insert into Member (id, name, email) values (89,'maria.mikkonen@gmail.com','Maria Mikkonen')
insert into Member (id, name, email) values (90,'maria.mikkonen@mli.hkkk.fi','maria.mikkonen@mli.hkkk.fi')
insert into Member (id, name, email) values (91,'marianne.kaplas@gmail.com','Mari')
insert into Member (id, name, email) values (92,'marjut_makinen@hotmail.com','Marjut Mäkinen')
insert into Member (id, name, email) values (93,'markus.ahlback@student.hse.fi','markus.ahlback@student.hse.fi')
insert into Member (id, name, email) values (94,'martin.yrjola@gmail.com','martin.yrjola@gmail.com')
insert into Member (id, name, email) values (95,'mauno.hellen@taloverkot.fi','mauno.hellen@taloverkot.fi')
insert into Member (id, name, email) values (96,'meri.miettinen@gmail.com','meri')
insert into Member (id, name, email) values (97,'mh7531@gmail.com','Mervi')
insert into Member (id, name, email) values (98,'mia.eklund@gmail.com','Mia Eklund')
insert into Member (id, name, email) values (99,'mika.ylikoski@gmail.com','Mika Ylikoski')
insert into Member (id, name, email) values (100,'mika.ylikoski@welho.com','mika.ylikoski@welho.com')
insert into Member (id, name, email) values (101,'mikko.iho@sappi.com','mikko.iho@sappi.com')
insert into Member (id, name, email) values (102,'mikko.kariola@gmail.com','mikko.kariola')
insert into Member (id, name, email) values (103,'mikko.lehmuskoski@gmail.com','Mikko Lehmuskoski')
insert into Member (id, name, email) values (104,'mirkka.siusluoto@gmail.com','Mirkka Siusluoto')
insert into Member (id, name, email) values (105,'mkorja@me.com','Miikka Korja')
insert into Member (id, name, email) values (106,'msildoja@gmail.com','msildoja@gmail.com')
insert into Member (id, name, email) values (107,'mystery320@gmail.com','Mikael Engström')
insert into Member (id, name, email) values (108,'nahlback@gmail.com','niklas ahlback')
insert into Member (id, name, email) values (109,'nikkeathome@gmail.com','-nikke-')
insert into Member (id, name, email) values (110,'niklas.ahlback@mli.hkkk.fi','niklas.ahlback@mli.hkkk.fi')
insert into Member (id, name, email) values (111,'nvaheri@gmail.com','Niina')
insert into Member (id, name, email) values (112,'oili.lahdenpera@gmail.com','Oili Lahdenperä')
insert into Member (id, name, email) values (113,'olli.sarkio@jippii.fi','olli.sarkio@jippii.fi')
insert into Member (id, name, email) values (114,'otto.sormunen@gmail.com','Otto Sormunen')
insert into Member (id, name, email) values (115,'otto@eirashipping.fi','Otto Reittilä')
insert into Member (id, name, email) values (116,'otto@surf.fi','Ode the Surffi')
insert into Member (id, name, email) values (117,'owillberg@hotmail.com','Oscar Willberg')
insert into Member (id, name, email) values (118,'paivi_korteniemi@hotmail.com','paivi_korteniemi@hotmail.com')
insert into Member (id, name, email) values (119,'pakarinen.a@gmail.com','Antsa')
insert into Member (id, name, email) values (120,'pekka.lindfors@iki.fi','pekka.lindfors@iki.fi')
insert into Member (id, name, email) values (121,'pekka.nortamo@luukku.com','Pekka Nortamo')
insert into Member (id, name, email) values (122,'pekka.vartiainen@ovi.com','Pekka Vartiainen')
insert into Member (id, name, email) values (123,'peltomaki.mikko@googlemail.com','Mikko Peltomäki')
insert into Member (id, name, email) values (124,'peter@surf.fi','peter@surf.fi')
insert into Member (id, name, email) values (125,'petiera@gmail.com','Petteri')
insert into Member (id, name, email) values (126,'Petri.Yrjola@valio.fi','Yrjölä Petri')
insert into Member (id, name, email) values (127,'pg.gust@gmail.com','PG')
insert into Member (id, name, email) values (128,'pipsa.salolammi@helsinki.fi','pipsa')
insert into Member (id, name, email) values (129,'psalolammi@hotmail.com','Pipsa')
insert into Member (id, name, email) values (130,'reetta.koski@gmail.com','Reetta')
insert into Member (id, name, email) values (131,'riikkaveera@gmail.com','Riikka Kankaanpää')
insert into Member (id, name, email) values (132,'riku.ruokolahti@gmail.com','riku.ruokolahti@gmail.com')
insert into Member (id, name, email) values (133,'risto.mononen@gmail.com','Risto')
insert into Member (id, name, email) values (134,'rm@surfing-ry.org','Risto Mononen')
insert into Member (id, name, email) values (135,'sami.urpila@gmail.com','Sami Urpila')
insert into Member (id, name, email) values (136,'samis.makinen@gmail.com','Sami Makinen')
insert into Member (id, name, email) values (137,'samuli.antikainen@finnair.fi','Samuli Antikainen')
insert into Member (id, name, email) values (138,'samuli7@gmail.com','k')
insert into Member (id, name, email) values (139,'sanna.paivarinta@gmail.com','Sanna')
insert into Member (id, name, email) values (140,'santtu.lescelius@gmail.com','Santtu')
insert into Member (id, name, email) values (141,'sofia.saarikko@gmail.com','Sofia Saarikko')
insert into Member (id, name, email) values (142,'sonja.ahlfors@iki.fi','Sonja Ahlfors')
insert into Member (id, name, email) values (143,'tanelivarjus@hotmail.com','tanelivarjus@hotmail.com')
insert into Member (id, name, email) values (144,'tanja.pasanen@helsinki.fi','Tanja pasanen')
insert into Member (id, name, email) values (145,'tarumaenp@gmail.com','Taru')
insert into Member (id, name, email) values (146,'tarumaenpaa@hotmail.com','Taru Mäenpää')
insert into Member (id, name, email) values (147,'tauno.perainen@fortum.com','Perainen Tauno')
insert into Member (id, name, email) values (148,'taunoperainen@hotmail.com','Surfing ry')
insert into Member (id, name, email) values (149,'teemu.paatela@gmail.com','Teemu Paatela')
insert into Member (id, name, email) values (150,'themeparty.fi@gmail.com','Theme Party')
insert into Member (id, name, email) values (151,'thero@me.com','thero')
insert into Member (id, name, email) values (152,'thomas.colerus@gmail.com','Thomas Colérus')
insert into Member (id, name, email) values (153,'tiia.nasanen@gmail.com','Tiia Näsänen')
insert into Member (id, name, email) values (154,'timo2rinne@gmail.com','Timo Rinne')
insert into Member (id, name, email) values (155,'tom.helenius@iki.fi','Tom Helenius')
insert into Member (id, name, email) values (156,'tomi.laine@strafica.fi','Tomi Laine')
insert into Member (id, name, email) values (157,'tomi@laine.fi','Tomi Laine')
insert into Member (id, name, email) values (158,'toni.ahola@kolumbus.fi','duracell')
insert into Member (id, name, email) values (159,'toni@surf.fi','Toni Ahola')
insert into Member (id, name, email) values (160,'tpoyhonen@gmail.com','Teemu Pöyhönen')
insert into Member (id, name, email) values (161,'tuomas.vuorinen@gmail.com','TuomasV')
insert into Member (id, name, email) values (162,'tuukka.anttolainen@gmail.com','Tuukka')
insert into Member (id, name, email) values (163,'valkonen.susanna@gmail.com','Susanna Valkonen')
insert into Member (id, name, email) values (164,'veehoo@gmail.com','veehoo')
insert into Member (id, name, email) values (165,'viialanposti@gmail.com','Jaakko Viiala')
insert into Member (id, name, email) values (166,'ville.holma@welho.com','Ville Holma')
insert into Member (id, name, email) values (167,'ville.wuotila@virmed.fi','ville.wuotila@virmed.fi')
insert into Member (id, name, email) values (168,'villefin89@gmail.com','Ville Niemi')
insert into Member (id, name, email) values (169,'villi@iki.fi','Ville Lindfors')
insert into Member (id, name, email) values (170,'vp.tynkkynen@elisanet.fi','vp.tynkkynen@elisanet.fi')
insert into Member (id, name, email) values (171,'zigaphau@gmail.com','MPTS')

