-- Initial values from mailing list 14 Apr 2013

insert into Member (id, name, email) values (1,'Antti Väänänen','a.tapio.vaananen@gmail.com')
insert into Member (id, name, email) values (2,'Andreas Ahlbäck','aahlback@cc.hut.fi')
insert into Member (id, name, email) values (3,'Aku','alitovaara@gmail.com')
insert into Member (id, name, email) values (4,'Andreas Ahlbäck','andreasahlback10@gmail.com')
insert into Member (id, name, email) values (5,'Anna Hakonen','anna.hakonen@helsinki.fi')
insert into Member (id, name, email) values (6,'Anna Palojärvi','anna.palojarvi@iki.fi')
insert into Member (id, name, email) values (7,'annaleena.ikkala@gmail.com','annaleena.ikkala@gmail.com')
insert into Member (id, name, email) values (8,'Anne','anne.j.dahlgren@gmail.com')
insert into Member (id, name, email) values (9,'CyberTiger','antony@cyberiantiger.org')
insert into Member (id, name, email) values (10,'Antti Känsälä','antti.kansala@gmail.com')
insert into Member (id, name, email) values (11,'puttonen','antti.vaananen@espoo.opit.fi')
insert into Member (id, name, email) values (12,'antti','antti@innamaa.com')
insert into Member (id, name, email) values (13,'Antti Niemi','apa@surf.fi')
insert into Member (id, name, email) values (14,'Carl-Johan Timgren','arvi.timgren@helsinki.fi')
insert into Member (id, name, email) values (15,'Beata Willman','beatawillman@gmail.com')
insert into Member (id, name, email) values (16,'Belina Björk','belina.bjork@gmail.com')
insert into Member (id, name, email) values (17,'Biju Surf','bijoux33@hotmail.com')
insert into Member (id, name, email) values (18,'Cathrine Henriksson','cathrineelisehenriksson@gmail.com')
insert into Member (id, name, email) values (19,'Christian','chrisseb@gmail.com')
insert into Member (id, name, email) values (20,'Daniel Blinnikka','danielblinnikka@gmail.com')
insert into Member (id, name, email) values (21,'Ylismaa Eeva','eeva.ylismaa@finnair.com')
insert into Member (id, name, email) values (22,'Ekku','ekku.rytkon@gmail.com')
insert into Member (id, name, email) values (23,'Esa Övermark','esa.overmark@gmail.com')
insert into Member (id, name, email) values (24,'Marius Marcellus','ewokmausoleum@gmail.com')
insert into Member (id, name, email) values (25,'Fabian Björk','fabian.bjork@aller.fi')
insert into Member (id, name, email) values (26,'Anders Smeds','fin312@gmail.com')
insert into Member (id, name, email) values (27,'Ninsku','hagman.niina@gmail.com')
insert into Member (id, name, email) values (28,'Issakainen Hanna','Hanna.Issakainen@parexel.com')
insert into Member (id, name, email) values (29,'Hanna Tukiainen','hanna.tukiainen@gmail.com')
insert into Member (id, name, email) values (30,'Heidi Harju','heidiharju1@gmail.com')
insert into Member (id, name, email) values (31,'Heidi Harju','heidiharju@welho.com')
insert into Member (id, name, email) values (32,'Heikki Winberg','heikki.winberg@iki.fi')
insert into Member (id, name, email) values (33,'heikki.ilvessalo@castren.fi','heikkiilvessalo@gmail.com')
insert into Member (id, name, email) values (34,'henkka.nyman@gmail.com','henkka.nyman@gmail.com')
insert into Member (id, name, email) values (35,'Henri Kronlund','henri.kronlund@gmail.com')
insert into Member (id, name, email) values (36,'hjunnila@cc.hut.fi','hjunnila@cc.hut.fi')
insert into Member (id, name, email) values (37,'Hanna Litovaara','hlitovaara@gmail.com')
insert into Member (id, name, email) values (38,'Mika Stenman','hlmika.stenman@gmail.com')
insert into Member (id, name, email) values (39,'Miia Holopainen','holopainen.miia@gmail.com')
insert into Member (id, name, email) values (40,'Ida Hakola','ida.hakola@gmail.com')
insert into Member (id, name, email) values (41,'Heino Immo','immo.heino@vtt.fi')
insert into Member (id, name, email) values (42,'Immo','immoheino@gmail.com')
insert into Member (id, name, email) values (43,'Jaan Praks','jaan.praks@tkk.fi')
insert into Member (id, name, email) values (44,'jaana.mellanen@luukku.com','jaana.mellanen@luukku.com')
insert into Member (id, name, email) values (45,'Jacke','jacob.segercrantz@gmail.com')
insert into Member (id, name, email) values (46,'Jani','jani.hienonen@gmail.com')
insert into Member (id, name, email) values (47,'Jani Paavolainen','jani.paavolainen@welho.com')
insert into Member (id, name, email) values (48,'surfing ry','janipaavolainen@gmail.com')
insert into Member (id, name, email) values (49,'Janne J','janne.junttila@luukku.com')
insert into Member (id, name, email) values (50,'Jari','jari.hamalainen@nice.fi')
insert into Member (id, name, email) values (51,'Jarno Lindblom','jarno@ddb.fi')
insert into Member (id, name, email) values (52,'Jenni Hovinen','jennihovinen@gmail.com')
insert into Member (id, name, email) values (53,'Broo Jesper','jesper.broo@processvision.fi')
insert into Member (id, name, email) values (54,'Johannes Haavanlammi','jhaavanlammi@gmail.com')
insert into Member (id, name, email) values (55,'Jarkko Sihvonen','jisihvon@cc.hut.fi')
insert into Member (id, name, email) values (56,'Jani','jkleinon@gmail.com')
insert into Member (id, name, email) values (57,'Juri Munkki','jmunkki@gmail.com')
insert into Member (id, name, email) values (58,'Johanna Ahtola','joahtola@gmail.com')
insert into Member (id, name, email) values (59,'JoGe','joge80@yahoo.com')
insert into Member (id, name, email) values (60,'joge@surf.fi','joge@surf.fi')
insert into Member (id, name, email) values (61,'Johanna Hinkkanen','johanna.eve@netti.fi')
insert into Member (id, name, email) values (62,'johannes.haavanlammi','johannes.haavanlammi@outotec.com')
insert into Member (id, name, email) values (63,'Jossu','johannes.kokkila@gmail.com')
insert into Member (id, name, email) values (64,'joonas_tuhkuri@hotmail.com','joonas_tuhkuri@hotmail.com')
insert into Member (id, name, email) values (65,'Josefine Hackman','josefine.hackman@gmail.com')
insert into Member (id, name, email) values (66,'josetez@wippies.fi','josetez@wippies.fi')
insert into Member (id, name, email) values (67,'juha.blinnikka@elisanet.fi','juha.blinnikka@elisanet.fi')
insert into Member (id, name, email) values (68,'Juha Haanperä','juhahaanpera@gmail.com')
insert into Member (id, name, email) values (69,'juhahaanpera@hotmail.com','juhahaanpera@hotmail.com')
insert into Member (id, name, email) values (70,'Juha Haanperä','juhahaanperasurfing@gmail.com')
insert into Member (id, name, email) values (71,'juho.mikkonen@kopparberg.fi','juho.mikkonen@kopparberg.fi')
insert into Member (id, name, email) values (72,'juhoik','juhoikkala@gmail.com')
insert into Member (id, name, email) values (73,'Jun Kojima','jun.kojima@vtt.fi')
insert into Member (id, name, email) values (74,'Jussi Harju','jussi.harju@steinmann.fi')
insert into Member (id, name, email) values (75,'Jussi','jussi.kallasvuo@gmail.com')
insert into Member (id, name, email) values (76,'Jusu','jusu1@kolumbus.fi')
insert into Member (id, name, email) values (77,'Kaarle Mäkinen','kaarle.makinen@gmail.com')
insert into Member (id, name, email) values (78,'Kaisa','kaisaryynanen@gmail.com')
insert into Member (id, name, email) values (79,'surffari','kalle_holle@hotmail.com')
insert into Member (id, name, email) values (80,'Kati','kati.hannukainen@gmail.com')
insert into Member (id, name, email) values (81,'Kim Hagman','kim.hagman@gmail.com')
insert into Member (id, name, email) values (82,'KirKir','kirill.tarassov@gmail.com')
insert into Member (id, name, email) values (83,'Kolari.Kari','kolari.kari@gmail.com')
insert into Member (id, name, email) values (84,'Kristian Englund','kristian.englund@gmail.com')
insert into Member (id, name, email) values (85,'Laura Puustinen','laura.puustinen@fimnet.fi')
insert into Member (id, name, email) values (86,'lauri','lauri.kajosaari@helsinki.fi')
insert into Member (id, name, email) values (87,'Maija','maija.salmela@tse.fi')
insert into Member (id, name, email) values (88,'Sanna','mail.moonfruit@gmail.com')
insert into Member (id, name, email) values (89,'Maria Mikkonen','maria.mikkonen@gmail.com')
insert into Member (id, name, email) values (90,'maria.mikkonen@mli.hkkk.fi','maria.mikkonen@mli.hkkk.fi')
insert into Member (id, name, email) values (91,'Mari','marianne.kaplas@gmail.com')
insert into Member (id, name, email) values (92,'Marjut Mäkinen','marjut_makinen@hotmail.com')
insert into Member (id, name, email) values (93,'markus.ahlback@student.hse.fi','markus.ahlback@student.hse.fi')
insert into Member (id, name, email) values (94,'martin.yrjola@gmail.com','martin.yrjola@gmail.com')
insert into Member (id, name, email) values (95,'mauno.hellen@taloverkot.fi','mauno.hellen@taloverkot.fi')
insert into Member (id, name, email) values (96,'meri','meri.miettinen@gmail.com')
insert into Member (id, name, email) values (97,'Mervi','mh7531@gmail.com')
insert into Member (id, name, email) values (98,'Mia Eklund','mia.eklund@gmail.com')
insert into Member (id, name, email) values (99,'Mika Ylikoski','mika.ylikoski@gmail.com')
insert into Member (id, name, email) values (100,'mika.ylikoski@welho.com','mika.ylikoski@welho.com')
insert into Member (id, name, email) values (101,'mikko.iho@sappi.com','mikko.iho@sappi.com')
insert into Member (id, name, email) values (102,'mikko.kariola','mikko.kariola@gmail.com')
insert into Member (id, name, email) values (103,'Mikko Lehmuskoski','mikko.lehmuskoski@gmail.com')
insert into Member (id, name, email) values (104,'Mirkka Siusluoto','mirkka.siusluoto@gmail.com')
insert into Member (id, name, email) values (105,'Miikka Korja','mkorja@me.com')
insert into Member (id, name, email) values (106,'msildoja@gmail.com','msildoja@gmail.com')
insert into Member (id, name, email) values (107,'Mikael Engström','mystery320@gmail.com')
insert into Member (id, name, email) values (108,'niklas ahlback','nahlback@gmail.com')
insert into Member (id, name, email) values (109,'-nikke-','nikkeathome@gmail.com')
insert into Member (id, name, email) values (110,'niklas.ahlback@mli.hkkk.fi','niklas.ahlback@mli.hkkk.fi')
insert into Member (id, name, email) values (111,'Niina','nvaheri@gmail.com')
insert into Member (id, name, email) values (112,'Oili Lahdenperä','oili.lahdenpera@gmail.com')
insert into Member (id, name, email) values (113,'olli.sarkio@jippii.fi','olli.sarkio@jippii.fi')
insert into Member (id, name, email) values (114,'Otto Sormunen','otto.sormunen@gmail.com')
insert into Member (id, name, email) values (115,'Otto Reittilä','otto@eirashipping.fi')
insert into Member (id, name, email) values (116,'Ode the Surffi','otto@surf.fi')
insert into Member (id, name, email) values (117,'Oscar Willberg','owillberg@hotmail.com')
insert into Member (id, name, email) values (118,'paivi_korteniemi@hotmail.com','paivi_korteniemi@hotmail.com')
insert into Member (id, name, email) values (119,'Antsa','pakarinen.a@gmail.com')
insert into Member (id, name, email) values (120,'pekka.lindfors@iki.fi','pekka.lindfors@iki.fi')
insert into Member (id, name, email) values (121,'Pekka Nortamo','pekka.nortamo@luukku.com')
insert into Member (id, name, email) values (122,'Pekka Vartiainen','pekka.vartiainen@ovi.com')
insert into Member (id, name, email) values (123,'Mikko Peltomäki','peltomaki.mikko@googlemail.com')
insert into Member (id, name, email) values (124,'peter@surf.fi','peter@surf.fi')
insert into Member (id, name, email) values (125,'Petteri','petiera@gmail.com')
insert into Member (id, name, email) values (126,'Yrjölä Petri','Petri.Yrjola@valio.fi')
insert into Member (id, name, email) values (127,'PG','pg.gust@gmail.com')
insert into Member (id, name, email) values (128,'pipsa','pipsa.salolammi@helsinki.fi')
insert into Member (id, name, email) values (129,'Pipsa','psalolammi@hotmail.com')
insert into Member (id, name, email) values (130,'Reetta','reetta.koski@gmail.com')
insert into Member (id, name, email) values (131,'Riikka Kankaanpää','riikkaveera@gmail.com')
insert into Member (id, name, email) values (132,'riku.ruokolahti@gmail.com','riku.ruokolahti@gmail.com')
insert into Member (id, name, email) values (133,'Risto','risto.mononen@gmail.com')
insert into Member (id, name, email) values (134,'Risto Mononen','rm@surfing-ry.org')
insert into Member (id, name, email) values (135,'Sami Urpila','sami.urpila@gmail.com')
insert into Member (id, name, email) values (136,'Sami Makinen','samis.makinen@gmail.com')
insert into Member (id, name, email) values (137,'Samuli Antikainen','samuli.antikainen@finnair.fi')
insert into Member (id, name, email) values (138,'k','samuli7@gmail.com')
insert into Member (id, name, email) values (139,'Sanna','sanna.paivarinta@gmail.com')
insert into Member (id, name, email) values (140,'Santtu','santtu.lescelius@gmail.com')
insert into Member (id, name, email) values (141,'Sofia Saarikko','sofia.saarikko@gmail.com')
insert into Member (id, name, email) values (142,'Sonja Ahlfors','sonja.ahlfors@iki.fi')
insert into Member (id, name, email) values (143,'tanelivarjus@hotmail.com','tanelivarjus@hotmail.com')
insert into Member (id, name, email) values (144,'Tanja pasanen','tanja.pasanen@helsinki.fi')
insert into Member (id, name, email) values (145,'Taru','tarumaenp@gmail.com')
insert into Member (id, name, email) values (146,'Taru Mäenpää','tarumaenpaa@hotmail.com')
insert into Member (id, name, email) values (147,'Perainen Tauno','tauno.perainen@fortum.com')
insert into Member (id, name, email) values (148,'Surfing ry','taunoperainen@hotmail.com')
insert into Member (id, name, email) values (149,'Teemu Paatela','teemu.paatela@gmail.com')
insert into Member (id, name, email) values (150,'Theme Party','themeparty.fi@gmail.com')
insert into Member (id, name, email) values (151,'thero','thero@me.com')
insert into Member (id, name, email) values (152,'Thomas Colérus','thomas.colerus@gmail.com')
insert into Member (id, name, email) values (153,'Tiia Näsänen','tiia.nasanen@gmail.com')
insert into Member (id, name, email) values (154,'Timo Rinne','timo2rinne@gmail.com')
insert into Member (id, name, email) values (155,'Tom Helenius','tom.helenius@iki.fi')
insert into Member (id, name, email) values (156,'Tomi Laine','tomi.laine@strafica.fi')
insert into Member (id, name, email) values (157,'Tomi Laine','tomi@laine.fi')
insert into Member (id, name, email) values (158,'duracell','toni.ahola@kolumbus.fi')
insert into Member (id, name, email) values (159,'Toni Ahola','toni@surf.fi')
insert into Member (id, name, email) values (160,'Teemu Pöyhönen','tpoyhonen@gmail.com')
insert into Member (id, name, email) values (161,'TuomasV','tuomas.vuorinen@gmail.com')
insert into Member (id, name, email) values (162,'Tuukka','tuukka.anttolainen@gmail.com')
insert into Member (id, name, email) values (163,'Susanna Valkonen','valkonen.susanna@gmail.com')
insert into Member (id, name, email) values (164,'veehoo','veehoo@gmail.com')
insert into Member (id, name, email) values (165,'Jaakko Viiala','viialanposti@gmail.com')
insert into Member (id, name, email) values (166,'Ville Holma','ville.holma@welho.com')
insert into Member (id, name, email) values (167,'ville.wuotila@virmed.fi','ville.wuotila@virmed.fi')
insert into Member (id, name, email) values (168,'Ville Niemi','villefin89@gmail.com')
insert into Member (id, name, email) values (169,'Ville Lindfors','villi@iki.fi')
insert into Member (id, name, email) values (170,'vp.tynkkynen@elisanet.fi','vp.tynkkynen@elisanet.fi')
insert into Member (id, name, email) values (171,'MPTS','zigaphau@gmail.com')